### ISSUE TITLE
Методы вкл и выкл кнопок объедини

### ISSUE THREAD

**Issue by parfenovvs** [alexsumin/myFileManager#3]
Типа setEnabledButtons(boolean isEnabled)

https://github.com/alexsumin/myFileManager/blob/8405163da986120d2dcc1c7d4aaa47d6ba98901d/src/main/java/ru/alexsumin/filemanager/view/MainWindowController.java#L119

**Comment by alexsumin** [comment]
Сделано, также поправил setExpanded
